on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Setup Playwright Environment
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      #       serve in non-blocking 8080 port using pm2
      - name: Serve Project Build
        run: ./node_modules/.bin/pm2 start npm -- run serve-p && ./node_modules/.bin/pm2 logs 0

      - name: Sleep for 30 seconds
        uses: whatnick/wait-action@master
        with:
          time: '30s'

      - name: Check if localhost is accesable
        uses: satak/webrequest-action@master
        with:
          url: http://localhost:8080
          method: GET

      - name: Run Tests
        run: npm run test
