on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Setup Playwright Environment
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Serve Project Build
        run: npx serve -s dist -l 8080

      - name: Run Tests
        run: npm run  test
