on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Setup Playwright Environment
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      #       serve in non-blocking 8080 port using pm2
      - name: Serve Project Build
        run: npm run serve-p

      - name: Run Tests
        run: npm run test
